# -*- coding: utf8 -*-
COUNTRY_CHOICES = ( 
('',u"--------"), 
(u"Afeganistão",u"Afeganistão"), 
(u"África do Sul",u"África do Sul"), 
(u"Albânia",u"Albânia"), 
(u"Alemanha",u"Alemanha"), 
(u"Andorra",u"Andorra"), 
(u"Angola",u"Angola"), 
(u"Anguila",u"Anguila"), 
(u"Antígua e Barbuda",u"Antígua e Barbuda"), 
(u"Antilhas Holandesas",u"Antilhas Holandesas"), 
(u"Arábia Saudita",u"Arábia Saudita"), 
(u"Argélia",u"Argélia"), 
(u"Argentina",u"Argentina"), 
(u"Armênia",u"Armênia"), 
(u"Austrália",u"Austrália"), 
(u"Áustria",u"Áustria"), 
(u"Azerbaijão",u"Azerbaijão"), 
(u"Bahamas",u"Bahamas"), 
(u"Bangladesh",u"Bangladesh"), 
(u"Barbados",u"Barbados"), 
(u"Barein",u"Barein"), 
(u"Belarus",u"Belarus"), 
(u"Bélgica",u"Bélgica"), 
(u"Belize",u"Belize"), 
(u"Benin",u"Benin"), 
(u"Bermudas",u"Bermudas"), 
(u"Bolívia",u"Bolívia"), 
(u"Bósnia-Herzegovina",u"Bósnia-Herzegovina"), 
(u"Botsuana",u"Botsuana"), 
(u"Brasil",u"Brasil"), 
(u"Brunei Darussalam",u"Brunei Darussalam"), 
(u"Bulgária",u"Bulgária"), 
(u"Burkina Fasso",u"Burkina Fasso"), 
(u"Burundi",u"Burundi"), 
(u"Butão",u"Butão"), 
(u"Cabo Verde",u"Cabo Verde"), 
(u"Camarões",u"Camarões"), 
(u"Camboja",u"Camboja"), 
(u"Canadá",u"Canadá"), 
(u"Catar",u"Catar"), 
(u"Cazaquistão",u"Cazaquistão"), 
(u"Chade",u"Chade"), 
(u"Chile",u"Chile"), 
(u"China",u"China"), 
(u"Chipre",u"Chipre"), 
(u"Cingapura",u"Cingapura"), 
(u"Colômbia",u"Colômbia"), 
(u"Comores",u"Comores"), 
(u"Congo",u"Congo"), 
(u"Coréia (República Democrática Popular da)",u"Coréia (República Democrática Popular da)"), 
(u"Costa do Marfim",u"Costa do Marfim"), 
(u"Costa Rica",u"Costa Rica"), 
(u"Croácia",u"Croácia"), 
(u"Cuba",u"Cuba"), 
(u"Dinamarca",u"Dinamarca"), 
(u"Djibuti",u"Djibuti"), 
(u"Dominica",u"Dominica"), 
(u"Egito",u"Egito"), 
(u"El Salvador",u"El Salvador"), 
(u"Emirados Árabes Unidos",u"Emirados Árabes Unidos"), 
(u"Equador",u"Equador"), 
(u"Eritréia",u"Eritréia"), 
(u"Eslováquia",u"Eslováquia"), 
(u"Eslovênia",u"Eslovênia"), 
(u"Espanha",u"Espanha"), 
(u"Estados Unidos",u"Estados Unidos"), 
(u"Estônia",u"Estônia"), 
(u"Etiópia",u"Etiópia"), 
(u"Federação dos Estados da Micronésia",u"Federação dos Estados da Micronésia"), 
(u"Federação Russa",u"Federação Russa"), 
(u"Fiji",u"Fiji"), 
(u"Filipinas",u"Filipinas"), 
(u"Finlândia",u"Finlândia"), 
(u"França",u"França"), 
(u"Gabão",u"Gabão"), 
(u"Gâmbia",u"Gâmbia"), 
(u"Gana",u"Gana"), 
(u"Geórgia",u"Geórgia"), 
(u"Geórgia do Sul",u"Geórgia do Sul"), 
(u"Gibraltar",u"Gibraltar"), 
(u"Granada",u"Granada"), 
(u"Grécia",u"Grécia"), 
(u"Groenlândia",u"Groenlândia"), 
(u"Guadalupe",u"Guadalupe"), 
(u"Guam",u"Guam"), 
(u"Guatemala",u"Guatemala"), 
(u"Guiana",u"Guiana"), 
(u"Guiana Francesa",u"Guiana Francesa"), 
(u"Guiné",u"Guiné"), 
(u"Guiné-Bissau",u"Guiné-Bissau"), 
(u"Guiné Equatorial",u"Guiné Equatorial"), 
(u"Haiti",u"Haiti"), 
(u"Holanda",u"Holanda"), 
(u"Honduras",u"Honduras"), 
(u"Hong Kong",u"Hong Kong"), 
(u"Hungria",u"Hungria"), 
(u"Iêmen",u"Iêmen"), 
(u"Ilha de Man",u"Ilha de Man"), 
(u"Ilha Norfolk",u"Ilha Norfolk"), 
(u"Ilhas Ascensão",u"Ilhas Ascensão"), 
(u"Ilhas Cayman",u"Ilhas Cayman"), 
(u"Ilhas Cook",u"Ilhas Cook"), 
(u"Ilhas Falkland (Malvinas)",u"Ilhas Falkland (Malvinas)"), 
(u"Ilhas Faroé",u"Ilhas Faroé"), 
(u"Ilhas Marianas do Norte",u"Ilhas Marianas do Norte"), 
(u"Ilhas Marshall",u"Ilhas Marshall"), 
(u"Ilhas Maurício",u"Ilhas Maurício"), 
(u"Ilhas Reunião",u"Ilhas Reunião"), 
(u"Ilhas Salomão",u"Ilhas Salomão"), 
(u"Ilhas Tokelau",u"Ilhas Tokelau"), 
(u"Ilhas Turks e Caicos",u"Ilhas Turks e Caicos"), 
(u"Ilhas Virgens (EUA)",u"Ilhas Virgens (EUA)"), 
(u"Ilhas Virgens (Reino Unido)",u"Ilhas Virgens (Reino Unido)"), 
(u"Ilhas Wallis e Futuna",u"Ilhas Wallis e Futuna"), 
(u"Índia",u"Índia"), 
(u"Indonésia",u"Indonésia"), 
(u"Irã",u"Irã"), 
(u"Iraque",u"Iraque"), 
(u"Irlanda",u"Irlanda"), 
(u"Islândia",u"Islândia"), 
(u"Israel",u"Israel"), 
(u"Itália",u"Itália"), 
(u"Iugoslávia",u"Iugoslávia"), 
(u"Jamaica",u"Jamaica"), 
(u"Japão",u"Japão"), 
(u"Jordânia",u"Jordânia"), 
(u"Kiribati",u"Kiribati"), 
(u"Kuwait",u"Kuwait"), 
(u"Laos",u"Laos"), 
(u"Lesoto",u"Lesoto"), 
(u"Letônia",u"Letônia"), 
(u"Líbano",u"Líbano"), 
(u"Libéria",u"Libéria"), 
(u"Líbia",u"Líbia"), 
(u"Liechtenstein",u"Liechtenstein"), 
(u"Lituânia",u"Lituânia"), 
(u"Luxemburgo",u"Luxemburgo"), 
(u"Macau",u"Macau"), 
(u"Macedônia",u"Macedônia"), 
(u"Madagascar",u"Madagascar"), 
(u"Maiote",u"Maiote"), 
(u"Malásia",u"Malásia"), 
(u"Malavi",u"Malavi"), 
(u"Maldivas",u"Maldivas"), 
(u"Mali",u"Mali"), 
(u"Malta",u"Malta"), 
(u"Marrocos",u"Marrocos"), 
(u"Martinica",u"Martinica"), 
(u"México",u"México"), 
(u"Moçambique",u"Moçambique"), 
(u"Moldávia",u"Moldávia"), 
(u"Mônaco",u"Mônaco"), 
(u"Mongólia",u"Mongólia"), 
(u"Montenegro",u"Montenegro"), 
(u"Montserrat",u"Montserrat"), 
(u"Myanmar",u"Myanmar"), 
(u"Namíbia",u"Namíbia"), 
(u"Nauru",u"Nauru"), 
(u"Nepal",u"Nepal"), 
(u"Nicarágua",u"Nicarágua"), 
(u"Níger",u"Níger"), 
(u"Nigéria",u"Nigéria"), 
(u"Niue",u"Niue"), 
(u"Noruega",u"Noruega"), 
(u"Nova Caledônia",u"Nova Caledônia"), 
(u"Nova Zelândia",u"Nova Zelândia"), 
(u"Omã",u"Omã"), 
(u"Palau",u"Palau"), 
(u"Panamá",u"Panamá"), 
(u"Papua-Nova Guiné",u"Papua-Nova Guiné"), 
(u"Paquistão",u"Paquistão"), 
(u"Paraguai",u"Paraguai"), 
(u"Peru",u"Peru"), 
(u"Pitcairn",u"Pitcairn"), 
(u"Polinésia Francesa",u"Polinésia Francesa"), 
(u"Polônia",u"Polônia"), 
(u"Porto Rico",u"Porto Rico"), 
(u"Portugal",u"Portugal"), 
(u"Quênia",u"Quênia"), 
(u"Quirguistão",u"Quirguistão"), 
(u"Reino Unido",u"Reino Unido"), 
(u"República Árabe da Síria",u"República Árabe da Síria"), 
(u"República Centro-Africana",u"República Centro-Africana"), 
(u"República da Coréia",u"República da Coréia"), 
(u"República Dominicana",u"República Dominicana"), 
(u"República Tcheca",u"República Tcheca"), 
(u"Romênia",u"Romênia"), 
(u"Ruanda",u"Ruanda"), 
(u"Samoa Americana",u"Samoa Americana"), 
(u"Samoa Ocidental",u"Samoa Ocidental"), 
(u"San Marino",u"San Marino"), 
(u"Santa Lúcia",u"Santa Lúcia"), 
(u"São Cristóvão e Névis",u"São Cristóvão e Névis"), 
(u"São Tomé e Príncipe",u"São Tomé e Príncipe"), 
(u"São Vicente e Granadinas",u"São Vicente e Granadinas"), 
(u"Seicheles",u"Seicheles"), 
(u"Senegal",u"Senegal"), 
(u"Serra Leoa",u"Serra Leoa"), 
(u"Sérvia",u"Sérvia"), 
(u"Somália",u"Somália"), 
(u"Sri Lanka",u"Sri Lanka"), 
(u"St. Pierre e Miquelon",u"St. Pierre e Miquelon"), 
(u"Suazilândia",u"Suazilândia"), 
(u"Sudão",u"Sudão"), 
(u"Suécia",u"Suécia"), 
(u"Suíça",u"Suíça"), 
(u"Suriname",u"Suriname"), 
(u"Tailândia",u"Tailândia"), 
(u"Taiwan",u"Taiwan"), 
(u"Tajiquistão",u"Tajiquistão"), 
(u"Tanzânia",u"Tanzânia"), 
(u"Território Oceânico Índico Britânico",u"Território Oceânico Índico Britânico"), 
(u"Togo",u"Togo"), 
(u"Tonga",u"Tonga"), 
(u"Trinidad e Tobago",u"Trinidad e Tobago"), 
(u"Tunísia",u"Tunísia"), 
(u"Turcomenistão",u"Turcomenistão"), 
(u"Turquia",u"Turquia"), 
(u"Tuvalu",u"Tuvalu"), 
(u"Ucrânia",u"Ucrânia"), 
(u"Uganda",u"Uganda"), 
(u"Uruguai",u"Uruguai"), 
(u"Uzbequistão",u"Uzbequistão"), 
(u"Vanuatu",u"Vanuatu"), 
(u"Venezuela",u"Venezuela"), 
(u"Vietnã",u"Vietnã"), 
(u"Zaire",u"Zaire"), 
(u"Zâmbia",u"Zâmbia"), 
(u"Zimbábue",u"Zimbábue"), 
) 
