insert into cadastro_feature (name, description, uri) VALUES ('home', 'Acessar a página inicial do sistema', 'home');
insert into cadastro_feature (name, description, uri) VALUES ('room', 'Listar, criar e editar salas', 'room');
insert into cadastro_feature (name, description, uri) VALUES ('stall', 'Listar, criar e editar baias', 'stall');
insert into cadastro_feature (name, description, uri) VALUES ('trainee', 'Listar, criar e editar bolsistas', 'trainee');
insert into cadastro_feature (name, description, uri) VALUES ('period', 'Listar, criar e editar periodos de bolsistas nas baias', 'period');
insert into cadastro_feature (name, description, uri) VALUES ('people', 'Listar, criar e editar pessoas', 'people');
insert into cadastro_feature (name, description, uri) VALUES ('device', 'Listar, criar e editar dispositivos', 'device');
insert into cadastro_feature (name, description, uri) VALUES ('categorydevice', 'Listar, criar e editar categorias de dispositivos', 'categorydevice');
insert into cadastro_feature (name, description, uri) VALUES ('institution', 'Listar, criar e editar instituições', 'institution');
insert into cadastro_feature (name, description, uri) VALUES ('user', 'Listar, criar e editar usuários', 'user');
insert into cadastro_feature (name, description, uri) VALUES ('report', 'Visualizar relatórios', 'report');
insert into cadastro_feature (name, description, uri) VALUES ('occupacy_report', 'Visualizar relatório por ocupação', 'occupacy_report');
